[versions]
agp = "8.9.2"
ksp = "2.1.0-1.0.29"
kotlin = "2.1.0"
serializationJson = "1.8.0"
jazzer = "0.22.1"
junit5 = "5.11.4"

coreKtx = "1.17.0"
startup = "1.2.0"
work = "2.11.0"
room = "2.7.1"
datastore = "1.2.0"

okhttp = "5.3.2"
coroutines = "1.10.2"

junit4 = "4.13.2"
truth = "1.4.5"
robolectric = "4.16"
androidxTestCore = "1.7.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver3", version.ref = "okhttp" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

junit4 = { module = "junit:junit", version.ref = "junit4" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
jazzer-junit = { module = "com.code-intelligence:jazzer-junit", version.ref = "jazzer" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
